version: '3'
services:
  rockpaperscissors-sql:
    image: microsoft/mssql-server-linux
    container_name: rockpaperscissors-sql
    environment:
        SA_PASSWORD: "M1cr0s0ft2018"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"

  rockpaperscissors-server:
    build:
      context: .
      dockerfile: Dockerfile-Server
    container_name: rockpaperscissors-server
    environment:
      "ConnectionStrings:DefaultConnection": "Server=rockpaperscissors-sql,1433;Database=RockPaperScissorsBoom;User Id=SA;Password=M1cr0s0ft2018;"
    ports:
        - "80:80"
    depends_on:
        - rockpaperscissors-sql